name: Deploy Portfolio to Github Pages

on:
    push:
        branches:
            - main

jobs: 
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            # Checout the repository
            - name: Checkout code
              uses: actions/checkout@v3  

            # Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20

            # Install Dependencies
            - name: Install Dependencies
              uses: npm install

            # Build Project
            - name: Build Project
              run: npm run build

            # Deploy 
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with: 
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: dist
              



